Towny:
    Guilds:
        Ranks:
            Halk:
                Name: §8ʜᴀʟᴋ
                Permissions: Donate
                Level: 1
            Paralı Asker:
                Name: §7ᴘᴀʀᴀʟı ᴀsᴋᴇʀ
                Permissions: Donate,Break,Place
                Level: 2
            Asker:
                Name: §2ᴀsᴋᴇʀ
                Permissions: Donate,Break,Place,Sethome,Claim
                Level: 3
            Vezir:
                Name: §5ᴠᴇᴢɪʀ
                Permissions: Donate,Break,Place,Sethome,Claim,Invite,Ally,War,Kick,Rank,Sethome
                Level: 4
            Lider:
                Name: §cʟɪᴅᴇʀ
                Permissions: Donate,Break,Place,Sethome,Claim,Invite,Ally,War,Kick,Rank,Sethome,Disband
    General:
        Teleport-Time: 5
        Nickel-To-Claim: 64
